FROM nginx:alpine

# Remove the default Nginx configuration
RUN rm /etc/nginx/conf.d/default.conf

# Copy the clean nginx.conf file you just created
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy your frontend files into the container
COPY frontend/ /usr/share/nginx/html/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]